blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'(?P<id>\d+)/post_edit/$', views.post_edit, name="post_edit"),
    url(r'(?P<id>\d+)/post_delete/$', views.post_delete, name="post_delete"),
    url(r'(?P<id>\d+)/favourite_post/$', views.favourite_post, name="favourite_post"),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.post_detail, name="post_detail"),
    url(r'post_create/$', views.post_create, name="post_create"),
    url(r'edit_profile/$', views.edit_profile, name="edit_profile"),
    url(r'favourites/$', views.post_favourite_list, name="post_favourite_list"),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from blog import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.post_list, name="post_list"),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^login/$', views.user_login, name="user_login"),
    url(r'^logout/$', views.user_logout, name="user_logout"),
    url(r'^register/$', views.register, name="register"),

    # Password Reset Url's
    # url(r'^password-reset/$', auth_views.password_reset, name="password_reset"),
    # url(r'^password-reset/done/$', auth_views.password_reset_done, name="password_reset_done"),
    # url(r'^password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', auth_views.password_reset_confirm, name="password_reset_confirm"),
    # url(r'^password-reset/complete/$', auth_views.password_reset_complete, name="password_reset_complete"),

    url(r'^', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace="social")),
    url(r'^like/', views.like_post, name="like_post"),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")

# Create your models here.
class Post(models.Model):
    objects = models.Manager()      #Our default Manager
    published = PublishedManager()  #Our Custom Model Manager

    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )

    title               =       models.CharField(max_length=100)
    slug                =       models.SlugField(max_length=120)
    author              =       models.ForeignKey(User, related_name='blog_posts')
    body                =       models.TextField()
    likes               =       models.ManyToManyField(User, related_name='likes', blank=True)
    created             =       models.DateTimeField(auto_now_add=True)
    updated             =       models.DateTimeField(auto_now=True)
    status              =       models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    restrict_comment    =       models.BooleanField(default=False)
    favourite           =       models.ManyToManyField(User, related_name='favourite', blank=True)



    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()


    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id, self.slug])

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(null=True, blank=True)


    def __str__(self):
        return "Profile of user {}".format(self.user.username)


class Images(models.Model):
    post = models.ForeignKey(Post)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return str(self.post.id)



class Comment(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User)
    reply = models.ForeignKey('Comment', null=True, related_name="replies")
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

blog/forms.py
from django import forms
from .models import Post, Profile, Comment
from django.contrib.auth.models import User

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'status',
            'restrict_comment',
        )

class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'status',
            'restrict_comment',
        )


class UserLoginForm(forms.Form):
    username = forms.CharField(label="")
    password = forms.CharField(label="", widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder':'Enter Password Here...'}))
    confirm_password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder':'Confirm Password...'}))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password


class UserEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)



class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!', 'rows':'4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from .models import Post, Profile, Images, Comment
from datetime import datetime
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.forms import modelformset_factory
from django.contrib import messages


# Create your views here.
def post_list(request):
    post_list = Post.published.all()
    query = request.GET.get('q')
    if query:
        post_list = Post.published.filter(
        Q(title__icontains=query)|
        Q(author__username=query)|
        Q(body__icontains=query)
        )
    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'posts': posts,
        'page_range': page_range,
    }
    return render(request, 'blog/post_list.html', context)

def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)


def post_detail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False
    is_favourite = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    if post.favourite.filter(id=request.user.id).exists():
        is_favourite = True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form= CommentForm()

    context = {
        'post': post,
        'is_liked': is_liked,
        'is_favourite': is_favourite,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'blog/post_detail.html', context)

def post_favourite_list(request):
    user = request.user
    favourite_posts = user.favourite.all()
    context = {
        'favourite_posts': favourite_posts,
    }
    return render(request, 'blog/post_favourite_list.html', context)

def favourite_post(request, id):
    post = get_object_or_404(Post, id=id)
    if post.favourite.filter(id=request.user.id).exists():
        post.favourite.remove(request.user)
    else:
        post.favourite.add(request.user)
    return HttpResponseRedirect(post.get_absolute_url())


def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})



def post_create(request):
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            print(formset.cleaned_data)
            for f in formset:
                print(f.cleaned_data)
                try:
                    photo = Images(post=post, image=f.cleaned_data.get('image'))
                    photo.save()
                except Exception as e:
                    break
            messages.success(request, "Post has been successfully created.")
            return redirect('post_list')
    else:
        form = PostCreateForm()
        formset = ImageFormset(queryset=Images.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'blog/post_create.html', context)

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4, max_num=4)
    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            print(formset.cleaned_data)
            data = Images.objects.filter(post=post)
            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = Images.objects.get(id=request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        d = Images.objects.get(id=data[index].id)
                        d.image = photo.image
                        d.save()
            messages.success(request, "{} has been successfully updated!".format(post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
        formset = ImageFormset(queryset=Images.objects.filter(post=post))
    context = {
    'form': form,
    'post': post,
    'formset': formset,
    }
    return render(request, 'blog/post_edit.html', context)




def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.author:
        raise Http404()
    post.delete()
    messages.warning(request, 'post has been successfully deleted!')
    return redirect('post_list')




def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    return HttpResponse("User is not active")
            else:
                return HttpResponse("User is None")
    else:
        form = UserLoginForm()

    context = {
        'form': form,
    }
    return render(request, 'blog/login.html', context)


def user_logout(request):
    logout(request)
    return redirect('post_list')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return redirect('post_list')
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'registration/register.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST or None, instance=request.user)
        profile_form = ProfileEditForm(data=request.POST or None, instance=request.user.profile, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            print(profile_form)
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse("blog:edit_profile"))
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'blog/edit_profile.html', context)

templates/blog/alerts.html
<div class="messages">
  {% if messages %}
    {% for message in messages %}
      <p class="alert alert-{{ message.tags }}">
        {{ message }}
      </p>
    {% endfor %}
  {% endif %}
</div>

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}AV's blog{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
  </head>
  <body>
    {% include 'blog/navbar.html' %}
    <div class="container-fluid">
      {% block content %}
      {% endblock %}
      {% include 'blog/footer.html' %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(event){
        $('#delete').click(function(){
          return confirm("Are you sure to delete this post?");
        });

        $('.reply-btn').click(function() {
          $(this).parent().parent().next('.replied-comments').fadeToggle()
        });


        $(function(){
          setTimeout(function(){
            $('.alert').slideUp(2000);
          }, 5000);
        });

        $(document).on('click', '#like', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "like_post" %}',
            data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: 'json',
            success: function(response){
              $('#like-section').html(response['form'])
              console.log($('#like-section').html(response['form']));
            },
            error: function(rs, e){
              console.log(rs.responseText);
            },
          });
        });

        $(document).on('submit', '.comment-form', function(event){
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
              $('.main-comment-section').html(response['form']);
              $('textarea').val('');
              $('.reply-btn').click(function() {
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                $('textarea').val('');
              });
            },
            error: function(rs, e) {
              console.log(rs.responseText);
            },
          });
        });


        $(document).on('submit', '.reply-form', function(event){
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
              $('.main-comment-section').html(response['form']);
              $('textarea').val('');
              $('.reply-btn').click(function() {
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                $('textarea').val('');
              });
            },
            error: function(rs, e) {
              console.log(rs.responseText);
            },
          });
        });

















      });
    </script>
  </body>
</html>

templates/blog/comments.html
<div class="container-fluid mt-2">
  <div class="form-group row">
    <form method="post" class="comment-form" action=".">
      {% csrf_token %}
      {{ comment_form.as_p }}
      {% if request.user.is_authenticated %}
        <input type="submit" value="Submit" class="btn btn-outline-success">
      {% else %}
        <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
      {% endif %}
    </form>
  </div>
</div>

{{ comments.count }} Comment{{ comments|pluralize }}
{% for comment in comments %}
  <blockquote class="blockquote">
    <p class="mb-0"><small>{{ comment.content }}</small></p>
    <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
      <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
    </footer>
  </blockquote>

  <div class="replied-comments container mt-2" style="display:none;">
    {% for reply in comment.replies.all %}
    <blockquote class="blockquote">
      <p class="mb-0"><small>{{ reply.content }}</small></p>
      <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
    </footer>
    </blockquote>
    {% endfor %}
    <div class="form-group row">
      <form method="post" class="reply-form" action=".">
        {% csrf_token %}
        <input type="hidden" name="comment_id" value="{{ comment.id }}">
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated %}
          <input type="submit" value="Submit" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
        {% endif %}
      </form>
    </div>
  </div>
{% endfor %}

templates/blog/edit_profile.html
{% extends 'blog/base.html' %}
{% block title %}Edit Profile | {{ block.super }}{% endblock %}
{% block content %}
  <form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Save Changes" class="btn btn-outline-success">
  </form>
{% endblock %}

templates/blog/footer.html
<footer class="footer text-white">
  <div class="row">
    <div class="col-md-4">
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
    </div>
    <div class="col-md-4">
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
    </div>
    <div class="col-md-4">
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
    </div>
  </div>
</footer>

templates/blog/like_section.html
{{ total_likes }} Like{{ total_likes|pluralize }}
{% if request.user.is_authenticated %}
<form action="{% url 'like_post' %}" method="post">
  {% csrf_token %}
  {% if is_liked %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-danger">Dislike</button>
  {% else %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
  {% endif %}
</form>
{% endif %}

templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <small>
        <a href="{% url 'register' %}">Register</a> |
        <a href="{% url 'password_reset' %}">Forgotten Your Password?</a>
      </small>
      <br>

    <input type="submit" value="Login" class="btn btn-outline-success">
    <p>-- OR --</p>
    <a href="{% url 'social:begin' 'github' %}">
      <button type="button" name="button" class="btn btn-primary">Github</button>
    </a>
    <a href="{% url 'social:begin' 'google-oauth2' %}">
      <button type="button" name="button" class="btn btn-danger">Google+</button>
    </a>
  </form>


{% endblock %}

templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="{% url 'post_list' %}">AV's Blog</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">

    <form class="form-inline my-2 my-lg-0" action='{% url 'post_list' %}'>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='q'>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

  </ul>
  <ul class="navbar-nav">
    {% if request.user.is_authenticated %}

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% if request.user.profile.photo %}
          <img src="{{ request.user.profile.photo.url }}" alt="" class="navbar-img">
        {% else %}
          <img src="/media/default-avatar.png" alt="" class="navbar-img">
        {% endif %}
        <span>Hi {{ request.user|capfirst }}</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'blog:edit_profile' %}">My Profile</a>
        <a class="dropdown-item" href="{% url 'blog:post_create' %}">Post Create</a>
        <a class="dropdown-item" href="{% url 'blog:post_favourite_list' %}">Favourite</a>
        <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
      </div>
    </li>
    {% else %}
    <li class="nav-item">
      <a href="{% url 'user_login' %}" class="nav-link">Login</a>
    </li>
    {% endif %}
  </ul>

</div>
</nav>

templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ formset.management_form }}
    {% for f in formset %}
      {{ f.as_p }}
    {% endfor %}
    <input type="submit" value="Create" class="btn btn-outline-success">
  </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }} | {{ block.super }}{% endblock %}

{% block content %}
{% include 'blog/alerts.html' %}


  <h3>{{ post.title }}</h3>
  <small>Post created by: {{ post.author }}</small>
  <hr>
  <p>{{ post.body }}</p>

  <div class="row gallery">
    {% for p in post.images_set.all %}
    {% if p.image %}
      <div class="col-md-3">
        <img src="{{ p.image.url }}" alt="Image Not Found" class="img-thumbnail">
      </div>
    {% endif %}
    {% endfor %}
  </div>

<div id="like-section">
  {% include 'blog/like_section.html' %}
</div>

<div id="favourite-section">
  {% if is_favourite %}
  <a href="{% url 'blog:favourite_post' id=post.id %}">
    <i class="fas fa-heart fa-lg"></i>
  </a>
  {% else %}
  <a href="{% url 'blog:favourite_post' id=post.id %}">
    <i class="far fa-heart fa-lg"></i>
  </a>
  {% endif %}
</div>


{% if post.author == request.user %}

<div class="section-1" style="float:right;">

  <a href="{% url 'blog:post_edit' id=post.id %}">
    <button type="button" class="btn btn-outline-success">Edit</button>
  </a>
  <a href="{% url 'blog:post_delete' id=post.id %}" id="delete">
    <button type="button" class="btn btn-danger">Delete</button>
  </a>
</div>
{% endif %}


<br><br>
<hr>

{% if not post.restrict_comment %}
  <div class="main-comment-section">
    {% include 'blog/comments.html' %}
  </div>
{% endif %}

{% endblock %}

templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}|Edit{% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ formset.management_form }}
    {% for f in formset %}
      {{ f.as_p }}
    {% endfor %}
    <input type="submit" value="Update" class="btn btn-success">
  </form>
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}Welcome to {{ block.super }}{% endblock %}

{% block content %}
{% include 'blog/alerts.html' %}


<div class="row">
  {% for p in posts %}
    <div class="col-md-6">
      <div class="img-thumbnail">
        <a href="{{ p.get_absolute_url }}">{{ p.title }}</a><small style="float:right">{{ p.created }}</small><br>
        Author: {{ p.author }}<br>
        {{ p.body }}
      </div>
      <br>
    </div>
  {% empty %}
      <div class="container-fluid">
        <h3>No Posts Found having search query "{{ request.GET.q }}"</h3>
      </div>

  {% endfor %}
</div>


<ul class="pagination">
  {% if posts.has_previous %}
    <li class="page-item">
      <a href="?page={{ posts.previous_page_number }}" class="page-link">&laquo;</a>
    </li>
  {% endif %}

  {% for p in page_range %}
    {% if posts.number == p %}
      <li class="page-item active">
        <a href="?page={{ p }}" class="page-link">{{ p }}</a>
      </li>
    {% else %}
      <li class="page-item">
        <a href="?page={{ p }}" class="page-link">{{ p }}</a>
      </li>
    {% endif %}
  {% endfor %}

  {% if posts.has_next %}
    <li class="page-item">
      <a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
    </li>
  {% endif %}
</ul>



{% endblock %}